apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: poddisruptionbudgets.policy.k8s.io
  annotations:
    api-approved.kubernetes.io: "https://github.com/kubernetes/enhancements/pull/1111"
spec:
  group: policy.k8s.io
  names:
    kind: PodDisruptionBudget
    plural: poddisruptionbudgets
    singular: poddisruptionbudget
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                minAvailable:
                  type: string
                maxUnavailable:
                  type: string
                selector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                    matchExpressions:
                      type: array
                      items:
                        type: object
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          values:
                            type: array
                            items:
                              type: string
            status:
              type: object
              properties:
                currentHealthy:
                  type: integer
                desiredHealthy:
                  type: integer
                disruptionsAllowed:
                  type: integer
                expectedPods:
                  type: integer
                observedGeneration:
                  type: integer
