apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: poddisruptionbudgets.policy.k8s.io
spec:
  group: policy.k8s.io
  names:
    kind: PodDisruptionBudget
    plural: poddisruptionbudgets
    singular: poddisruptionbudget
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true